### ISSUE TITLE
The required namespace "fulcro.inspect.client" is not available

### ISSUE THREAD

**Issue by Lokeh** [nubank/workspaces#13]
I'm currently using this in a vanilla React project. I get this error when compilation begins with the latest version `1.0.0-preview6`:

```
shadow.user> (shadow/watch :workspaces)
[:workspaces] Configuring build.
[:workspaces] Compiling ...
[:workspaces] Build failure:
The required namespace "fulcro.inspect.client" is not available, it was required by "nubank/workspaces/card_types/fulcro.cljs".
```

Downgrading to `1.0.0-preview5` works as expected.

**Comment by wilkerlucio** [comment]
@Lokeh thanks for the report! From preview 5 to 6 I tried to clean the deps a bit, seems like was too much 😅

I pushed `1.0.0-preview7` putting some of those deps back, can you please try and see if that works?

**Comment by Lokeh** [comment]
:+1: `1.0.0-preview7` fixed this particular issue, but it's still necessary to install transit-clj for `https://github.com/nubank/workspaces/issues/12` - closing this.
