### ISSUE TITLE
Card errors can prevent workspaces from working

### ISSUE THREAD

**Issue by wilkerlucio** [nubank/workspaces#14]
Right now if an error happens during a card render that can prevent workspaces from loading, it should be more resilient and tolerate user errors.

**Comment by awkay** [comment]
Easy reproducible case:

A card without a query will cause workspaces to flicker like mad and be unusable as it tries to restart instead of just saying the card is crap.

```
(defsc WashProgamList [this props]
  (dom/div "TODO"))

(ws/defcard wash-program-list-card
  {::wsm/card-width 4 ::wsm/card-height 4}
  (ct.fulcro/fulcro-card
    {::f.portal/root WashProgamList}))
```

**Comment by wilkerlucio** [comment]
Are you using `preview9`? This should be fixed there

**Comment by awkay** [comment]
preview9 does seem to fix it. Thanks.
