### ISSUE TITLE
shadow-cljs target broken

### ISSUE THREAD

**Issue by thheller** [nubank/workspaces#42]
In shadow-cljs `2.9.x` I removed the classpath indexing since it was causing a lot of issues and didn't provide much. It did however provide the `classpath/get-all-resources` fn which is used here:

https://github.com/nubank/workspaces/blob/689fbefd22faa8c48403f3f1e41b6708f2a7b209/src/nubank/workspaces/shadow_cljs/target.clj#L10

This no longer provides the necessary data and fails. I migrated all the official test targets to use the alternative instead which restores that functionality. You could either use the provided helper fn directly or use the replacement `find-cljs-namespaces-in-files` fn if you want more custom filtering. 

- https://github.com/thheller/shadow-cljs/blob/d80ee477020c91fa441bb205f52967c1100e2526/src/main/shadow/build/test_util.clj#L6
- https://github.com/thheller/shadow-cljs/blob/d80ee477020c91fa441bb205f52967c1100e2526/src/main/shadow/build/targets/node_test.clj#L42
- https://github.com/thheller/shadow-cljs/blob/d80ee477020c91fa441bb205f52967c1100e2526/src/main/shadow/build/test_util.clj#L15

**Comment by awkay** [comment]
Excellent. Thanks!

**Comment by MrEbbinghaus** [comment]
This can be closed, doesn't it?
