### ISSUE TITLE
Small shadow-cljs related tweaks

### ISSUE THREAD

**Issue by thheller** [nubank/workspaces#7]
Hey there, this is really cool!

You could make some small tweaks to make config a bit easier.

The `myapp.workspaces.main` could be completely optional if you instead change the build config to:

```
:modules
{:main
    {:entries
     [myapp.workspaces.cards
      myapp.workspaces.custom-card
      myapp.workspaces.fulcro-demo-cards
      myapp.workspaces.reframe-demo-cards]
     :init-fn nubank.workspaces.core/mount}}
```

It is exactly equivalent to the current `.main` in the `examples` directory. Totally fine to use the `ns` over the config though. With some small adjustments you could also use the `:browser-test` target instead and use `:ns-regexp "-cards$"` so you don't have to list them all.

You can also change the `nubank.workspaces.core` to use the lifecycle metadata hooks so the user doesn't have to configure them at all.

```
(defn before-load
  {:dev/before-load true}
  []
  (reset! data/card-definitions-snap* @data/card-definitions*))

(defn after-load
  {:dev/after-load true}
  []
  (ui/refresh-active-workspace-cards (:reconciler @data/app*))
  (reset! data/card-definitions-snap* @data/card-definitions*))
```

**Comment by wilkerlucio** [comment]
Nice! I didn't know about those shadow facilities, I'll update the examples. One thing I'm curious, if I change the `:entries` and save the shadow file, a running watch will update or I would have to start and stop the build when adding new entries?

**Comment by thheller** [comment]
Config changes will be detected and the watch will be restarted. Although I do have to check if new `:entries` are properly loaded. They should be though.

**Comment by wilkerlucio** [comment]
Fixed in master, the hooks are set and documentation updated. I decided to keep just the main method for now, but I wanna try and document better using `:init-fn` / `:browser-test`at some point, thanks for the tips!
